---
title: "Introduction to grammar of graphics"
author: "Murray Logan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
    css: ../resources/style.css
  pdf_document:
    df_print: default
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: tango
    latex_engine: xelatex
    number_sections: yes
    toc_depth: 2
  word_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: tango
    toc: yes
    toc_depth: 2
output_dir: "docs"
documentclass: article
fontsize: 12pt
mainfont: Arial
mathfont: LiberationMono
monofont: DejaVu Sans Mono
classoption: a4paper
bibliography: ../resources/references.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparations

Load the necessary libraries

```{r libraries, results='markdown', eval=TRUE, message=FALSE, warning=FALSE}
library(tidyverse) #for data wrangling
theme_set(theme_classic())
library(grid)
library(patchwork)
library(scales)
library(gridExtra)
load(file='../data/manipulationDatasets.RData')
```

Graphics infrastructure
========================

- **layers** of data driven objects
- **coord**inate system
- **scales**
- **faceting**
- **themes**


Motivating data
-----------------

```{r, results='markup'}
head(BOD)
summary(BOD)
BOD <- rename(BOD, time = Time)
```

Layers
==========

- **layers** of data driven objects
    - **geom**etric objects to represent data
    - **stat**istical methods to summarize the data
    - **mapping** of aesthetics
    - **position** control

## geom_point
```{r}
ggplot(data = BOD, aes(y = demand, x = time)) +
  geom_line(aes(col = time)) +
  geom_point(aes(col = demand, size=demand)) +
  scale_color_viridis_c() +
  guides(color = guide_legend(title = "Time"),
         size = guide_legend(title = "Demand")) +
  labs(x = "Time", y = "Demand")
```

```{r}
ggplot(CO2, aes(y = uptake, x = conc)) + 
  geom_point()+
  scale_x_log10(name = "CO2 conc",
    breaks = as.vector(c(1, 2, 5, 10) %o% 10^(-1:2)))

# works well to create nice breaks around 1, 2, 5, and 10 at different log scales!
c(1, 2, 5, 10) %o% 10^(-1:2)
```



Primary geometric objects
===========================

`geom_bar`
------------
```{r}

```



`geom_boxplot`
----------------


`geom_line`
-------------


`geom_point`
------------

`geom_smooth`
------------

`geom_polygon`
----------------

`geom_tile`
----------------

`geom_raster`
----------------

Secondary geometric objects
============================

`geom_errorbar`
------------------

`geom_pointrange`
------------------

Coordinate systems
====================


Scales
==========

`scale_x_` and `scale_y_`
----------------------------

Other scales
---------------

- **size** of points (thickness of lines)
- **shape** of points
- **linetype** of lines
- **color** of lines or points
- **fill** of shapes

`scale_size`
----------------

`scale_shape`
----------------

`scale_linetype`
----------------

`scale_fill` and `scale_color`
-------------------------------

```{r}
state=data.frame(state.x77, state.region, state.division, state.center) %>%
    select(Illiteracy, state.region, x, y)
head(state)

state %>%
  group_by(state.region) %>%
  summarise(mean_il = mean(Illiteracy),
            se_il = sd(Illiteracy) / sqrt( n() ),
            lwr_il = gmodels::ci(Illiteracy)[2],
            upr_il = gmodels::ci(Illiteracy)[3]) %>%
  ggplot(aes(x = state.region, y = mean_il, fill=state.region)) +
  geom_col() +
  geom_pointrange(aes(ymin = lwr_il, ymax = upr_il)) +
  labs(x = "Region", y = "Mean Illiteracy (%)")
```

Facets
==========

Themes
==========

`theme_classic`
----------------

`theme_bw`
----------------

`theme_grey`
----------------

`theme_minimal`
----------------

`theme_linedraw`
----------------

Practice
===========
